'use client'

import { useState, type FormEvent } from 'react'
import Link from 'next/link'
import { useCart } from './CartProvider'
import { useCommerce } from './CommerceProvider'
import { formatUyu } from '@/lib/order'
import type { FulfillmentType, Order } from '@/data/types'
import styles from './Checkout.module.css'

export function Checkout() {
  const cart=useCart(); const commerce=useCommerce(); const defaultFulfillment: FulfillmentType=commerce.settings.pickupEnabled?'pickup':'delivery'; const [fulfillment,setFulfillment]=useState<FulfillmentType>(defaultFulfillment); const [error,setError]=useState(''); const [order,setOrder]=useState<Order|null>(null)
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const form=new FormData(event.currentTarget);try{const created=commerce.placeOrder(cart.lines,{customer:{name:String(form.get('name')),phone:String(form.get('phone')),email:String(form.get('email')??'')},fulfillment,address:String(form.get('address')??''),notes:String(form.get('notes')??'')});setOrder(created);cart.clear()}catch(reason){setError(reason instanceof Error?reason.message:'No pudimos crear el pedido.')}}
  if(order)return <main className={styles.shell}><section className={styles.confirm}><p className="kicker">Pedido recibido</p><h1>¡Gracias!</h1><p>Tu pedido <strong>#{order.number}</strong> ya fue recibido.</p><Link className="btn btnPrimary" href={`/pedido/${order.trackingToken}`}>Ver estado del pedido</Link></section></main>
  const fee=fulfillment==='delivery'?commerce.settings.deliveryFeeCents:0
  return <main className={styles.shell}><Link href="/#menu" className="ruleLink">← Volver a la carta</Link><h1>Finalizar pedido</h1>{!commerce.settings.orderingOpen?<p>Los pedidos están cerrados. Horario: {commerce.settings.orderHours}</p>:!cart.lines.length?<p>Tu carrito está vacío.</p>:<form onSubmit={submit}><section><h2>Datos de contacto</h2><label>Nombre completo<input required minLength={2} name="name" autoComplete="name"/></label><label>Teléfono<input required minLength={6} name="phone" inputMode="tel" autoComplete="tel"/></label><label>Email (opcional)<input name="email" type="email" autoComplete="email"/></label></section><section><h2>Entrega</h2><div className={styles.choice}>{commerce.settings.pickupEnabled&&<label><input type="radio" checked={fulfillment==='pickup'} onChange={()=>setFulfillment('pickup')}/> Retiro en el local</label>}{commerce.settings.deliveryEnabled&&<label><input type="radio" checked={fulfillment==='delivery'} onChange={()=>setFulfillment('delivery')}/> Delivery</label>}</div>{fulfillment==='delivery'&&<><label>Dirección<input required name="address" autoComplete="street-address"/></label><p className={styles.hint}>Costo: {formatUyu(fee)} · Mínimo: {formatUyu(commerce.settings.deliveryMinimumCents)}</p></>}<label>Observaciones generales<textarea name="notes" maxLength={500}/></label></section><section><h2>Resumen</h2>{cart.lines.map(line=><div className={styles.summary} key={line.key}><span>{line.quantity} × {line.name}{line.selections.map(choice=><small key={choice.choiceId}> · {choice.name}</small>)}</span><span>{formatUyu((line.unitPriceCents+line.selections.reduce((sum,item)=>sum+item.priceCents,0))*line.quantity)}</span></div>)}{fee>0&&<div className={styles.summary}><span>Delivery</span><span>{formatUyu(fee)}</span></div>}<div className={styles.total}><strong>Total</strong><strong>{formatUyu(cart.total+fee)}</strong></div><p className={styles.hint}>{commerce.settings.orderHours} · Pago al recibir o retirar.</p>{error&&<p role="alert" className={styles.error}>{error}</p>}<button className="btn btnPrimary">Confirmar pedido</button></section></form>}</main>
}
