-- La Toscana e-commerce foundation. Additive migration; no existing object is removed.
create extension if not exists pgcrypto;
create type public.order_status as enum ('pending','confirmed','preparing','ready','delivering','completed','cancelled');
create type public.fulfillment_type as enum ('delivery','pickup');

create table public.business_settings (id boolean primary key default true check(id), name text not null, phone text not null, address text not null default '', delivery_enabled boolean not null default true, pickup_enabled boolean not null default true, delivery_fee_cents integer not null default 0 check(delivery_fee_cents>=0), updated_at timestamptz not null default now());
create table public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, sort_order integer not null default 0, available boolean not null default true, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), external_id text unique not null, category_id uuid not null references public.categories(id), name text not null, description text not null default '', price_cents integer not null check(price_cents>=0), available boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_options (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, name text not null, required boolean not null default false, min_choices integer not null default 0, max_choices integer not null default 1, sort_order integer not null default 0, check(min_choices>=0 and max_choices>=min_choices));
create table public.option_choices (id uuid primary key default gen_random_uuid(), option_id uuid not null references public.product_options(id) on delete cascade, name text not null, price_delta_cents integer not null default 0, available boolean not null default true, sort_order integer not null default 0);
create table public.orders (id uuid primary key default gen_random_uuid(), number bigint generated always as identity unique, tracking_token uuid unique not null default gen_random_uuid(), status public.order_status not null default 'pending', fulfillment_type public.fulfillment_type not null, customer_name text not null, customer_phone text not null, customer_email text, delivery_address text, customer_notes text, subtotal_cents integer not null check(subtotal_cents>=0), delivery_fee_cents integer not null default 0 check(delivery_fee_cents>=0), total_cents integer not null check(total_cents>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, unit_price_cents integer not null, quantity integer not null check(quantity between 1 and 20), notes text, line_total_cents integer not null);
create table public.order_item_choices (order_item_id uuid not null references public.order_items(id) on delete cascade, choice_id uuid references public.option_choices(id) on delete set null, choice_name text not null, price_delta_cents integer not null, primary key(order_item_id,choice_name));
create table public.order_status_history (id bigint generated always as identity primary key, order_id uuid not null references public.orders(id) on delete cascade, status public.order_status not null, changed_by uuid references auth.users(id), created_at timestamptz not null default now());

alter table public.business_settings enable row level security; alter table public.admin_users enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.product_options enable row level security; alter table public.option_choices enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.order_item_choices enable row level security; alter table public.order_status_history enable row level security;
create function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()) $$;
revoke all on function public.is_admin() from public; grant execute on function public.is_admin() to authenticated;
create policy "public catalog read" on public.categories for select using(available); create policy "public product read" on public.products for select using(available); create policy "public option read" on public.product_options for select using(exists(select 1 from public.products p where p.id=product_id and p.available)); create policy "public choice read" on public.option_choices for select using(available);
create policy "admins business" on public.business_settings for all to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admins categories" on public.categories for all to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admins products" on public.products for all to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admins options" on public.product_options for all to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admins choices" on public.option_choices for all to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admins orders" on public.orders for all to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admins items" on public.order_items for select to authenticated using(public.is_admin()); create policy "admins item choices" on public.order_item_choices for select to authenticated using(public.is_admin()); create policy "admins history" on public.order_status_history for select to authenticated using(public.is_admin());

create function public.create_public_order(payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare new_order public.orders; item jsonb; product public.products; item_id uuid; choices_total integer; subtotal integer:=0; fee integer:=0;
begin
  if jsonb_array_length(payload->'items') not between 1 and 50 then raise exception 'invalid items'; end if;
  if length(trim(payload#>>'{customer,name}')) not between 2 and 120 or length(trim(payload#>>'{customer,phone}')) not between 6 and 40 then raise exception 'invalid customer'; end if;
  if payload->>'fulfillment'='delivery' and length(trim(coalesce(payload->>'address',''))) < 5 then raise exception 'address required'; end if;
  for item in select * from jsonb_array_elements(payload->'items') loop
    select * into product from public.products where external_id=item->>'productId' and available for share;
    if not found or (item->>'quantity')::integer not between 1 and 20 then raise exception 'invalid product'; end if;
    select coalesce(sum(c.price_delta_cents),0) into choices_total from public.option_choices c join public.product_options o on o.id=c.option_id where c.id in (select value::uuid from jsonb_array_elements_text(coalesce(item->'optionChoiceIds','[]'::jsonb))) and c.available and o.product_id=product.id;
    subtotal:=subtotal+(product.price_cents+choices_total)*(item->>'quantity')::integer;
  end loop;
  if payload->>'fulfillment'='delivery' then select delivery_fee_cents into fee from public.business_settings where id=true; fee:=coalesce(fee,0); end if;
  insert into public.orders(fulfillment_type,customer_name,customer_phone,customer_email,delivery_address,customer_notes,subtotal_cents,delivery_fee_cents,total_cents) values ((payload->>'fulfillment')::public.fulfillment_type,trim(payload#>>'{customer,name}'),trim(payload#>>'{customer,phone}'),nullif(trim(payload#>>'{customer,email}'),''),nullif(trim(payload->>'address'),''),left(payload->>'notes',500),subtotal,fee,subtotal+fee) returning * into new_order;
  for item in select * from jsonb_array_elements(payload->'items') loop
    select * into product from public.products where external_id=item->>'productId'; select coalesce(sum(c.price_delta_cents),0) into choices_total from public.option_choices c join public.product_options o on o.id=c.option_id where c.id in (select value::uuid from jsonb_array_elements_text(coalesce(item->'optionChoiceIds','[]'::jsonb))) and c.available and o.product_id=product.id;
    insert into public.order_items(order_id,product_id,product_name,unit_price_cents,quantity,notes,line_total_cents) values(new_order.id,product.id,product.name,product.price_cents,(item->>'quantity')::integer,left(item->>'notes',300),(product.price_cents+choices_total)*(item->>'quantity')::integer) returning id into item_id;
    insert into public.order_item_choices(order_item_id,choice_id,choice_name,price_delta_cents) select item_id,c.id,c.name,c.price_delta_cents from public.option_choices c join public.product_options o on o.id=c.option_id where c.id in(select value::uuid from jsonb_array_elements_text(coalesce(item->'optionChoiceIds','[]'::jsonb))) and c.available and o.product_id=product.id;
  end loop;
  insert into public.order_status_history(order_id,status) values(new_order.id,new_order.status);
  return jsonb_build_object('number',new_order.number::text,'trackingToken',new_order.tracking_token);
end $$;
revoke all on function public.create_public_order(jsonb) from public; grant execute on function public.create_public_order(jsonb) to anon;
create function public.get_public_order(lookup_token uuid) returns jsonb language sql stable security definer set search_path='' as $$ select jsonb_build_object('number',number::text,'status',status,'fulfillment',fulfillment_type,'total_cents',total_cents,'created_at',created_at) from public.orders where tracking_token=lookup_token $$;
revoke all on function public.get_public_order(uuid) from public; grant execute on function public.get_public_order(uuid) to anon;
create function public.log_order_status() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status is distinct from old.status then insert into public.order_status_history(order_id,status,changed_by) values(new.id,new.status,auth.uid()); end if; new.updated_at=now(); return new; end $$;
create trigger order_status_audit before update on public.orders for each row execute function public.log_order_status();

-- Initial catalog mirrors the approved landing; subsequent edits happen in admin.
insert into public.business_settings(id,name,phone,address) values(true,'La Toscana','093 379 047','Florida, Uruguay');
insert into public.categories(slug,name,sort_order) values ('pastas','Pastas',10),('pizzas','Pizzas',20),('carnes','Carnes',30),('picadas','Picadas',40),('postres','Postres',50),('vinos','Vinos',60);
insert into public.products(external_id,category_id,name,description,price_cents,sort_order)
select v.external_id,c.id,v.name,v.description,v.price_cents,v.sort_order from (values
('sorrentinos-jyq','pastas','Sorrentinos de jamón y queso','Hechos en casa, salsa a elección',59000,10),('tallarines-toscana','pastas','Tallarines a la Toscana','Crema, panceta y champiñones',54000,20),('noquis-papa','pastas','Ñoquis de papa','Bolognesa o cuatro quesos',52000,30),('lasana-carne','pastas','Lasaña de carne','Gratinada al horno',62000,40),('muzzarella-piedra','pizzas','Muzzarella a la piedra','Salsa de tomate y aceitunas',43000,10),('napolitana','pizzas','Napolitana','Tomate fresco, ajo y albahaca',48000,20),('toscana-especial','pizzas','Toscana especial','Jamón crudo, rúcula y parmesano',56000,30),('entrecot-parrilla','carnes','Entrecot a la parrilla','Con papas rústicas',78000,10),('pollo-champinon','carnes','Pollo al champiñón','Suprema con salsa cremosa',62000,20),('picada-dos','picadas','Picada para dos','Fiambres, quesos y frituras',89000,10),('tabla-mar','picadas','Tabla de mar','Rabas, langostinos y limón',98000,20),('tiramisu','postres','Tiramisú','Receta clásica de la casa',32000,10),('flan-casero','postres','Flan casero','Con dulce de leche',26000,20),('tannat-reserva','vinos','Tannat Reserva','Copa o botella',38000,10),('chardonnay','vinos','Chardonnay','Copa o botella',36000,20)
) as v(external_id,slug,name,description,price_cents,sort_order) join public.categories c on c.slug=v.slug;
